# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "groups", :force => true do |t|
    t.column "name", :string, :limit => 80
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "map_nodes", :force => true do |t|
    t.column "name", :string, :limit => 100
    t.column "description", :string, :limit => 400
    t.column "text", :string, :limit => 4000
  end

  create_table "map_paths", :id => false, :force => true do |t|
    t.column "source_id", :integer
    t.column "dest_id", :integer
  end

  create_table "meetings", :force => true do |t|
    t.column "name", :string, :limit => 80
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "npc", :force => true do |t|
    t.column "name", :string
    t.column "description", :string
    t.column "map_node", :integer
  end

  create_table "roles", :force => true do |t|
    t.column "name", :string, :limit => 40
    t.column "authorizable_type", :string, :limit => 30
    t.column "authorizable_id", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "user_id", :integer
    t.column "role_id", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "users", :force => true do |t|
    t.column "username", :string, :limit => 80
    t.column "password_salt", :string
    t.column "password_hash", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

end
